config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  resources :conventions do
    resources :deliveries
  end
  resources :line_items
  resources :carts
  resources :deliveries do
    get :autocomplete_convention_libelle, :on => :collection
  end
  get 'locale=:locale' => 'store#index'
  get 'store/index'
  root :to => 'store#index', :as => 'store'
  resources :products

end

app/models/convention.rb
class Convention < ActiveRecord::Base
  has_many :delivery, :dependent => :destroy
  #scope :conventionuser , -> { order(:libelle) }
  default_scope  { order(:libelle) }
  accepts_nested_attributes_for :delivery, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true
  
end

app/controllers/conventions_controller.rb
class ConventionsController < ApplicationController
 
  def index
    @convention = Convention.all
  end
  def new
    @convention = Convention.new
    delivery = @convention.delivery.build
  end
  def update
    @convention = Convention.find(params[:id])
    respond_to do |format|
      if @convention.update_attributes(convention_params)
        format.html { redirect_to @convention, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @convention }
      else
        format.html { render :edit }
        format.json { render json: @convention.errors, status: :unprocessable_entity }
      end
    end
  end

  def create
    @convention = Convention.new(convention_params)

    respond_to do |format|
      if @convention.save
        format.html { redirect_to @convention, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @convention }
      else
        format.html { render :new }
        format.json { render json: @convention.errors, status: :unprocessable_entity }
      end
    end
  end
    # Never trust parameters from the scary internet, only allow the white list through.
  def convention_params
    params.require(:convention).permit(:libelle)
    end
  def show
    @convention = Convention.find(params[:id])
  end
  def edit
    @convention = Convention.find(params[:id])
  end

end

app/helpers/convention_helper.rb
module ConventionHelper
end

app/views/conventions/_delivery_fields.html.erb
<tr>
  <td>
    <p class="field">
    <%= f.input :libelle %>
    <%= f.hidden_field :_destroy %>
    <%= link_to_remove_fields "Supprimer", f %> 
    </p>
  </td>
</tr>

app/views/conventions/edit.html.erb
<h1>Editing product</h1>
<%= form_for(@convention) do |f| %>
  <div class="field">
    <%= f.label :libelle %><br>
    <%= f.text_field :libelle %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<%= link_to 'Back', conventions_path %>

app/views/conventions/index.html.erb
<table>
  <thead>
    <tr>
      <th>Libelle</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @convention.each do |convention| %>
      <tr class="<%= cycle('list_line_odd','list_line_even') %>">
        <td><%= convention.libelle %></td>
        <td><%= link_to 'Show', convention %></td>
        <td><%= link_to 'Edit', edit_convention_path(convention) %></td>
        <td><%= link_to 'Destroy', convention, method: :delete, data: { confirm: 'Etes-vous sure ?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/conventions/new.html.erb
<h1>Nouveau Contrat</h1>

<%= simple_form_for @convention do |f| %>
  <%= f.input :libelle, label_html: { class: 'my_class' } %>
<table>
  <tr>
    <th>Deliveries</th>
  </tr>
  <%= f.fields_for :delivery do |builder| %>
    <%= render "delivery_fields", :f => builder %>
  <% end %>
</table>
<p><%= link_to_add_fields "Ajouter un delivery", f, :deliveries %></p>
  <%= f.button :submit %>
<% end %>

app/views/conventions/show.html.erb
<table border=0><tr><td>Titre de convention :</td><td><%= @convention.libelle %></td></tr>
  <tr><td>Crée le :</td><td><%= I18n.localize(@convention.created_at, :format => :short) %></td></tr>
  <tr><td>Modifié le :</td><td><%= I18n.localize(@convention.updated_at, :format => :short) %></td></tr>
</table>
<table style="border: solid 1px;" ><tr><th>Deliveries</th></tr>
<% @convention.delivery.each do |delivery| %>
<tr><td><%= delivery.libelle %></td></tr>
<% end %>
</table>